apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
    - subnet: 192.168.1.0/24
      pool: 192.168.1.100-192.168.254.128
      aggregation: default
