---
apiVersion: v1
kind: Namespace
metadata:
  name: meetup-generator
  labels:
    name: meetup-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meetup-generator
  name: meetup-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meetup-generator
  template:
    metadata:
      labels:
        app: meetup-generator
    spec:
      containers:
      - name: meetup-generator-container
        image: snltd/meetup-generator:1.7.5
        ports:
        - containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
    name: meetup-generator
    namespace: meetup-generator
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.100
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
  selector:
    app: meetup-generator
